export default testData = [
  {
    selectedCity: 'İstanbul',
    selectedDistrict: 'Kadıköy',
    name: 'Kemal Kılıçdaroğlu',
    boxNumber: '1259',
    votePerc: 0.5248,
    voteCount: 321,
    styleCandi: 'kk',
    photoURL: require(`./../../assets/kk.png`),
  },
  {
    selectedCity: 'İstanbul',
    selectedDistrict: 'Üsküdar',
    name: 'Recep Tayyip Erdoğan',
    boxNumber: '1314',
    votePerc: 0.5135,
    voteCount: 284,
    styleCandi: 'rte',
    photoURL: require(`./../../assets/rte.png`),
  },
  {
    selectedCity: 'İstanbul',
    selectedDistrict: 'Kadıköy',
    name: 'Kemal Kılıçdaroğlu',
    boxNumber: '1259',
    votePerc: 0.5178,
    voteCount: 246,
    styleCandi: 'kk',
    photoURL: require(`./../../assets/kk.png`),
  },
  {
    selectedCity: 'İstanbul',
    selectedDistrict: 'Kadıköy',
    name: 'Recep Tayyip Erdoğan',
    boxNumber: '1489',
    votePerc: 0.5324,
    voteCount: 289,
    styleCandi: 'rte',
    photoURL: require(`./../../assets/rte.png`),
  },
];
